# Generated by Django 5.0.6 on 2024-06-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='color',
            field=models.CharField(default='black', max_length=10),
            preserve_default=False,
        ),
    ]
