# Generated by Django 5.0.6 on 2024-06-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_player_no_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
    ]
